import Head from 'next/head';
import styles from '../styles/Layout.module.css';
import Footer from './Footer';
import Header from './Header';

export default function Layout({ children }) {
  return (
    <div className={styles.LayoutMainContainer}>
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Amazon Clone" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="icon" type="image/png" href="/icons/icon-256x256.png" /> */}
        <link rel="manifest" href="/manifest.json" />
        <link rel="shortcut icon" href="/icons/icon-256x256.png" />
      </Head>

      <div className={styles.LayoutMainContent}>
        {/* Header */}
        <Header />
        {children}
      </div>

      {/* Footer */}
      <Footer />
    </div>
  );
}
