import Head from 'next/head';
import styles from '../styles/Layout.module.css';
import Header from './Header';

export default function Layout({ children }) {
  return (
    <div className={styles.LayoutMainContainer}>
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Amazon Clone" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.LayoutMainContent}>
        {/* Header */}
        <Header />
        {children}
      </div>
      <h1>Footer</h1>

      {/* Footer */}
    </div>
  );
}
